# path: src/automation/cad_script_generator.py

"""
CADScriptGenerator

Added generation of simulation-ready scripts (new JuniorPython feature).
"""

from typing import Any, Dict, List, Optional
import time

try:
    from src.quantization.hybrid_squeeze_bitnet import HybridSqueezeBitNetQuantizer
except ImportError:
    HybridSqueezeBitNetQuantizer = None


class CADScriptGenerator:
    def __init__(self, hybrid_quantizer: Optional[Any] = None):
        self.hybrid_quantizer = hybrid_quantizer or (HybridSqueezeBitNetQuantizer() if HybridSqueezeBitNetQuantizer else None)
        self.supported_formats = ["openscad", "python_cadquery", "step", "freecad", "optimization_script", "simulation_script"]
        self._generation_count = 0
        self._total_generation_time = 0.0

    def _parse_design_params(self, design_state: Any) -> Dict[str, Any]:
        if hasattr(design_state, "to_dict"):
            data = design_state.to_dict()
        elif isinstance(design_state, dict):
            data = design_state
        else:
            data = {"params": getattr(design_state, "params", {}), "metrics": getattr(design_state, "metrics", {})}

        params = data.get("params", {})
        metrics = data.get("metrics", {})

        return {
            "wing_sweep": float(params.get("wing_sweep", 35.0)),
            "nose_shape": str(params.get("nose_shape", "ogive")).lower(),
            "length": float(params.get("length", 30.0)),
            "drag": float(metrics.get("drag_coefficient", 0.02)),
            "boom": float(metrics.get("boom_overpressure", 1.0)),
        }

    def _quantize_features(self, features: Dict[str, float]) -> Dict[str, float]:
        if not self.hybrid_quantizer:
            return features
        quantized = {}
        for key, value in features.items():
            try:
                q_val = self.hybrid_quantizer.quantize([value])
                quantized[key] = float(q_val[0]) if hasattr(q_val, "__len__") else float(q_val)
            except Exception:
                quantized[key] = value
        return quantized

    def generate_simulation_script(self, design_state: Any) -> str:
        """Generate a simulation-ready script (new JuniorPython feature for CFD/FEA)."""
        start = time.time()
        params = self._parse_design_params(design_state)
        q_params = self._quantize_features({k: v for k, v in params.items() if isinstance(v, (int, float))})

        script = f"""# Simulation Script - Generated by JuniorCloud CADScriptGenerator
# {time.strftime("%Y-%m-%d %H:%M:%S")}
# BitNet-optimized parameters for supersonic design

wing_sweep = {q_params.get("wing_sweep", 35)}
length = {q_params.get("length", 30)}

print("Preparing simulation for design with wing sweep:", wing_sweep)

# Example: OpenFOAM case setup or simple CFD parameters
print("Mesh settings: length =", length)
print("Angle of attack simulation ready.")

# Placeholder for actual simulation runner
print("Run CFD/FEA here...")
"""
        self._generation_count += 1
        self._total_generation_time += time.time() - start
        return script

    def generate_openscad(self, design_state: Any) -> str:
        start = time.time()
        params = self._parse_design_params(design_state)
        q_params = self._quantize_features({k: v for k, v in params.items() if isinstance(v, (int, float))})

        script = f"""// JuniorCloud CADScriptGenerator (HybridSqueezeBitNet optimized)
// {time.strftime("%Y-%m-%d %H:%M:%S")}

wing_sweep = {q_params.get("wing_sweep", 35)};
nose_shape = "{params.get("nose_shape", "ogive")}";
length = {q_params.get("length", 30)};

module fuselage() {{
    cylinder(h = length, r1 = 1.5, r2 = 0.8, center = true);
}}

module wing() {{
    rotate([0, 0, wing_sweep])
    cube([length * 0.6, 0.3, 8], center = true);
}}

module nose() {{
    if (nose_shape == "ogive") {{
        translate([0, 0, length/2]) sphere(r = 1.2);
    }} else {{
        translate([0, 0, length/2]) cylinder(h = 3, r1 = 1.5, r2 = 0.5);
    }}
}}

fuselage();
wing();
nose();
"""
        self._generation_count += 1
        self._total_generation_time += time.time() - start
        return script

    def generate_python_cadquery(self, design_state: Any, export_step: bool = False, direct_step_filename: Optional[str] = None) -> str:
        start = time.time()
        params = self._parse_design_params(design_state)
        q_params = self._quantize_features({k: v for k, v in params.items() if isinstance(v, (int, float))})

        step_code = ""
        if export_step or direct_step_filename:
            step_code = "result.val().exportStep('" + (direct_step_filename or "design.step") + "')"

        script = f"""# JuniorCloud CADScriptGenerator (HybridSqueezeBitNet optimized)
# {time.strftime("%Y-%m-%d %H:%M:%S")}

import cadquery as cq

wing_sweep = {q_params.get("wing_sweep", 35)}
nose_shape = "{params.get("nose_shape", "ogive")}"
length = {q_params.get("length", 30)}

result = (
    cq.Workplane("XY")
    .cylinder(length, 1.5)
    .faces(">Z").workplane().circle(0.8).extrude(length * 0.3)
)

wing = (
    cq.Workplane("XY")
    .rect(length * 0.6, 8)
    .extrude(0.3)
    .rotate((0, 0, 0), (0, 0, 1), wing_sweep)
)

result = result.union(wing)

if nose_shape == "ogive":
    nose = cq.Workplane("XY").sphere(1.2).translate((0, 0, length/2))
else:
    nose = cq.Workplane("XY").cylinder(3, 1.5).translate((0, 0, length/2))

result = result.union(nose)

{step_code}
print("CAD generated with BitNet efficiencies.")
"""
        self._generation_count += 1
        self._total_generation_time += time.time() - start
        return script

    def generate_step(self, design_state: Any, filename: str = "design.step") -> bool:
        try:
            params = self._parse_design_params(design_state)
            q_params = self._quantize_features({k: v for k, v in params.items() if isinstance(v, (int, float))})

            import cadquery as cq
            result = (
                cq.Workplane("XY")
                .cylinder(params["length"], 1.5)
                .faces(">Z").workplane().circle(0.8).extrude(params["length"] * 0.3)
            )
            wing = (
                cq.Workplane("XY")
                .rect(params["length"] * 0.6, 8)
                .extrude(0.3)
                .rotate((0, 0, 0), (0, 0, 1), params["wing_sweep"])
            )
            result = result.union(wing)

            if params["nose_shape"] == "ogive":
                nose = cq.Workplane("XY").sphere(1.2).translate((0, 0, params["length"]/2))
            else:
                nose = cq.Workplane("XY").cylinder(3, 1.5).translate((0, 0, params["length"]/2))

            result = result.union(nose)
            result.val().exportStep(filename)
            self._generation_count += 1
            return True
        except Exception as e:
            print(f"[CADScriptGenerator] Direct STEP export error: {e}")
            return False

    def generate_freecad_macro(self, design_state: Any) -> str:
        params = self._parse_design_params(design_state)
        return f"""# FreeCAD Macro - Generated by JuniorCloud (HybridSqueezeBitNet optimized)
# {time.strftime("%Y-%m-%d %H:%M:%S")}

print("FreeCAD macro for design with sweep {params.get('wing_sweep')}")
"""

    def generate_optimization_script(self, design_state: Any) -> str:
        start = time.time()
        params = self._parse_design_params(design_state)
        q_params = self._quantize_features({k: v for k, v in params.items() if isinstance(v, (int, float))})

        script = f"""# Optimization Script - Generated by JuniorCloud CADScriptGenerator
# {time.strftime("%Y-%m-%d %H:%M:%S")}
# BitNet-optimized parameters

wing_sweep = {q_params.get("wing_sweep", 35)}
length = {q_params.get("length", 30)}

print("Starting optimization for wing sweep:", wing_sweep)

for i in range(10):
    current_drag = 0.02 - (i * 0.001)
    print(f"Iteration {{i}}: drag = {{current_drag:.4f}}")

print("Optimization complete.")
"""
        self._generation_count += 1
        self._total_generation_time += time.time() - start
        return script

    def generate_script(self, design_state: Any, format: str = "openscad") -> str:
        if format == "openscad":
            return self.generate_openscad(design_state)
        elif format == "python_cadquery":
            return self.generate_python_cadquery(design_state)
        elif format == "step":
            return self.generate_python_cadquery(design_state, export_step=True)
        elif format == "freecad":
            return self.generate_freecad_macro(design_state)
        elif format == "optimization_script":
            return self.generate_optimization_script(design_state)
        elif format == "simulation_script":
            return self.generate_simulation_script(design_state)
        else:
            raise ValueError(f"Unsupported format: {format}")

    def export_to_file(self, design_state: Any, filename: str, format: str = "openscad") -> bool:
        try:
            if format == "step":
                return self.generate_step(design_state, filename)
            script = self.generate_script(design_state, format=format)
            with open(filename, "w") as f:
                f.write(script)
            return True
        except Exception as e:
            print(f"[CADScriptGenerator] Export error: {e}")
            return False

    def get_efficiency_report(self) -> Dict[str, Any]:
        avg_time = self._total_generation_time / max(self._generation_count, 1)
        return {
            "scripts_generated": self._generation_count,
            "total_generation_time": self._total_generation_time,
            "avg_time_per_script": avg_time
        }


if __name__ == "__main__":
    from src.design.vlm_design_agent import DesignState

    test_design = DesignState(
        params={"wing_sweep": 48, "nose_shape": "ogive", "length": 32},
        metrics={"drag_coefficient": 0.011, "boom_overpressure": 0.55}
    )

    gen = CADScriptGenerator()
    print(gen.generate_script(test_design, "simulation_script"))
