# path: src/automation/cad_script_generator.py

"""
CADScriptGenerator

JuniorPython automation layer for CAD/script generation tied to the design agent.

Features:
- Generates OpenSCAD and Python (cadquery) scripts from DesignState
- Uses BitNet efficiencies where possible (quantized feature processing)
- Proper data parsing and formatting for clean, executable scripts
- Blackbox modular design - can be piped from VLMDesignAgent
- Elite systems: robust error handling, type safety, efficient serialization

This enables the VLMDesignAgent to output production-ready CAD scripts for rapid prototyping and iteration toward supersonic designs.
"""

from typing import Any, Dict, List, Optional
import json
import time

try:
    from src.quantization.hybrid_squeeze_bitnet import HybridSqueezeBitNetQuantizer
except ImportError:
    HybridSqueezeBitNetQuantizer = None


class CADScriptGenerator:
    def __init__(self, hybrid_quantizer: Optional[Any] = None):
        self.hybrid_quantizer = hybrid_quantizer or (HybridSqueezeBitNetQuantizer() if HybridSqueezeBitNetQuantizer else None)
        self.supported_formats = ["openscad", "python_cadquery"]

    def _parse_design_params(self, design_state: Any) -> Dict[str, Any]:
        """Robust parsing of DesignState or dict into clean parameters."""
        if hasattr(design_state, "to_dict"):
            data = design_state.to_dict()
        elif isinstance(design_state, dict):
            data = design_state
        else:
            data = {"params": getattr(design_state, "params", {}), "metrics": getattr(design_state, "metrics", {})}

        params = data.get("params", {})
        metrics = data.get("metrics", {})

        # Normalize common supersonic design keys
        normalized = {
            "wing_sweep": float(params.get("wing_sweep", 35.0)),
            "nose_shape": str(params.get("nose_shape", "ogive")).lower(),
            "length": float(params.get("length", 30.0)),
            "drag": float(metrics.get("drag_coefficient", 0.02)),
            "boom": float(metrics.get("boom_overpressure", 1.0)),
        }
        return normalized

    def _quantize_features(self, features: Dict[str, float]) -> Dict[str, float]:
        """Apply BitNet hybrid quantization to numerical features for efficiency."""
        if not self.hybrid_quantizer:
            return features

        quantized = {}
        for key, value in features.items():
            try:
                # Simple scalar quantization via the hybrid quantizer
                q_val = self.hybrid_quantizer.quantize([value])
                quantized[key] = float(q_val[0]) if hasattr(q_val, "__len__") else float(q_val)
            except Exception:
                quantized[key] = value  # fallback
        return quantized

    def generate_openscad(self, design_state: Any, filename: str = "design.scad") -> str:
        """Generate clean OpenSCAD script from design state."""
        params = self._parse_design_params(design_state)
        q_params = self._quantize_features({k: v for k, v in params.items() if isinstance(v, (int, float))})

        script = f"""// Generated by JuniorCloud CADScriptGenerator
// Timestamp: {time.strftime("%Y-%m-%d %H:%M:%S")}
// Design params (quantized where applicable)

wing_sweep = {q_params.get("wing_sweep", 35)};
nose_shape = "{params.get("nose_shape", "ogive")}";
length = {q_params.get("length", 30)};

// Simple supersonic fuselage + wing
module fuselage() {{
    cylinder(h = length, r1 = 1.5, r2 = 0.8, center = true);
}}

module wing() {{
    rotate([0, 0, wing_sweep])
    cube([length * 0.6, 0.3, 8], center = true);
}}

module nose() {{
    if (nose_shape == "ogive") {{
        translate([0, 0, length/2])
        sphere(r = 1.2);
    }} else {{
        translate([0, 0, length/2])
        cylinder(h = 3, r1 = 1.5, r2 = 0.5);
    }}
}}

fuselage();
wing();
nose();

// Metrics comment for reference
// drag: {params.get("drag", 0)}
// boom: {params.get("boom", 0)}
"""
        return script

    def generate_python_cadquery(self, design_state: Any, filename: str = "design.py") -> str:
        """Generate Python script using cadquery (more powerful for FEA/CFD prep)."""
        params = self._parse_design_params(design_state)
        q_params = self._quantize_features({k: v for k, v in params.items() if isinstance(v, (int, float))})

        script = f"""# Generated by JuniorCloud CADScriptGenerator
# Timestamp: {time.strftime("%Y-%m-%d %H:%M:%S")}
# BitNet-optimized parameters for efficient local generation

import cadquery as cq

wing_sweep = {q_params.get("wing_sweep", 35)}
nose_shape = "{params.get("nose_shape", "ogive")}"
length = {q_params.get("length", 30)}

# Fuselage
result = (
    cq.Workplane("XY")
    .cylinder(length, 1.5)
    .faces(">Z")
    .workplane()
    .circle(0.8)
    .extrude(length * 0.3)
)

# Wing (simplified)
wing = (
    cq.Workplane("XY")
    .rect(length * 0.6, 8)
    .extrude(0.3)
    .rotate((0, 0, 0), (0, 0, 1), wing_sweep)
)

result = result.union(wing)

# Nose
if nose_shape == "ogive":
    nose = cq.Workplane("XY").sphere(1.2).translate((0, 0, length/2))
else:
    nose = cq.Workplane("XY").cylinder(3, 1.5).translate((0, 0, length/2))

result = result.union(nose)

# Export
result.val().exportStep("{filename.replace('.py', '.step')}")
print("CAD generated successfully with BitNet efficiencies.")
"""
        return script

    def generate_script(self, design_state: Any, format: str = "openscad") -> str:
        """Main entry point - dispatches to correct format with proper parsing."""
        if format not in self.supported_formats:
            raise ValueError(f"Unsupported format: {format}. Choose from {self.supported_formats}")

        if format == "openscad":
            return self.generate_openscad(design_state)
        elif format == "python_cadquery":
            return self.generate_python_cadquery(design_state)

    def export_to_file(self, design_state: Any, filename: str, format: str = "openscad"):
        """Generate and write script to file with elite error handling."""
        try:
            script = self.generate_script(design_state, format=format)
            with open(filename, "w") as f:
                f.write(script)
            return True
        except Exception as e:
            print(f"[CADScriptGenerator] Export error: {e}")
            return False


if __name__ == "__main__":
    from src.design.vlm_design_agent import DesignState

    test_design = DesignState(
        params={"wing_sweep": 48, "nose_shape": "ogive", "length": 32},
        metrics={"drag_coefficient": 0.011, "boom_overpressure": 0.55}
    )

    generator = CADScriptGenerator()
    scad_script = generator.generate_script(test_design, format="openscad")
    print("OpenSCAD script generated successfully (BitNet optimized).")
    print(scad_script[:300] + "...")
